name: pyzip # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Easy to use, Python-based, Zip and Unzip tool.
description: |
  Easy to use, Python-based, Zip and Unzip tool.

apps:
  pyzip:
    command: python3 pyZip.py

parts:
  main:
    plugin: python3
    source: https://github.com/electrodeyt/pyzip.git
    source-type: git
